package org.ecoinformatics.sms.annotation.persistent.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.ecoinformatics.sms.annotation.persistent.DbObservation;

/**
 * Class _DbAnnotation was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _DbAnnotation extends CayenneDataObject {

    public static final String DATA_TABLE_PROPERTY = "dataTable";
    public static final String EML_PACKAGE_PROPERTY = "emlPackage";
    public static final String IDENTIFIER_PROPERTY = "identifier";
    public static final String SOURCE_PROPERTY = "source";
    public static final String OBSERVATIONS_PROPERTY = "observations";

    public static final String ID_PK_COLUMN = "id";

    public void setDataTable(String dataTable) {
        writeProperty("dataTable", dataTable);
    }
    public String getDataTable() {
        return (String)readProperty("dataTable");
    }

    public void setEmlPackage(String emlPackage) {
        writeProperty("emlPackage", emlPackage);
    }
    public String getEmlPackage() {
        return (String)readProperty("emlPackage");
    }

    public void setIdentifier(String identifier) {
        writeProperty("identifier", identifier);
    }
    public String getIdentifier() {
        return (String)readProperty("identifier");
    }

    public void setSource(String source) {
        writeProperty("source", source);
    }
    public String getSource() {
        return (String)readProperty("source");
    }

    public void addToObservations(DbObservation obj) {
        addToManyTarget("observations", obj, true);
    }
    public void removeFromObservations(DbObservation obj) {
        removeToManyTarget("observations", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<DbObservation> getObservations() {
        return (List<DbObservation>)readProperty("observations");
    }


}
