package org.ecoinformatics.sms.annotation.persistent.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.ecoinformatics.sms.annotation.persistent.DbCharacteristic;
import org.ecoinformatics.sms.annotation.persistent.DbObservation;

/**
 * Class _DbMeasurement was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _DbMeasurement extends CayenneDataObject {

    public static final String PROTOCOL_PROPERTY = "protocol";
    public static final String STANDARD_PROPERTY = "standard";
    public static final String TEMPLATE_PROPERTY = "template";
    public static final String CHARACTERISTICS_PROPERTY = "characteristics";
    public static final String OBSERVATION_PROPERTY = "observation";

    public static final String ID_PK_COLUMN = "id";

    public void setProtocol(String protocol) {
        writeProperty("protocol", protocol);
    }
    public String getProtocol() {
        return (String)readProperty("protocol");
    }

    public void setStandard(String standard) {
        writeProperty("standard", standard);
    }
    public String getStandard() {
        return (String)readProperty("standard");
    }

    public void setTemplate(String template) {
        writeProperty("template", template);
    }
    public String getTemplate() {
        return (String)readProperty("template");
    }

    public void addToCharacteristics(DbCharacteristic obj) {
        addToManyTarget("characteristics", obj, true);
    }
    public void removeFromCharacteristics(DbCharacteristic obj) {
        removeToManyTarget("characteristics", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<DbCharacteristic> getCharacteristics() {
        return (List<DbCharacteristic>)readProperty("characteristics");
    }


    public void setObservation(DbObservation observation) {
        setToOneTarget("observation", observation, true);
    }

    public DbObservation getObservation() {
        return (DbObservation)readProperty("observation");
    }


}
